### ISSUE TITLE
Live Docs not matching main branch

### ISSUE THREAD

**Issue by nattyxd** [aws/aws-emr-best-practices#12]
Hey Folks,

I was taking a read through the EMR best practices over at https://aws.github.io/aws-emr-best-practices/features/managed_scaling/best_practices/ and noticed a typo "YARNMeoryAvailablePercentage". I came to submit a PR but noticed it has already been fixed.

Commit where changes were made: https://github.com/aws/aws-emr-best-practices/commit/d3730bc715a1b909c55ab650e830675beba9b980

Yet the changes don't seem to be live, perhaps CI/CD is broken? I don't think it'll be a cache problem (I checked in an incognito page in case) given the age of the commit.

Let me know if I can be of any use, all the best

**Comment by mattliemAWS** [comment]
thanks for catching this, nattyxd. We merged changes to mainline but didnt push to mkdocs. fixed now

**Comment by nattyxd** [comment]
thank you @mattliemAWS
