### ISSUE TITLE
Create entry in BP 4.2.6 for Small Spark Task Size

### ISSUE THREAD

**Issue by secretazianman** [aws/aws-emr-best-practices#8]
Adjusting Spark task size to something that can be finished in less than 2 minutes reduces the impact of spot loss, especially in the case of no shuffle or cached data. In a simulated test with FIS interrupting all EMR Task nodes 3 times over, we notice just 3 failures out of 100k tasks, with a 10 sec task size.

**Comment by mattliemAWS** [comment]
thanks. this was already captured in Bp 4.2.6 but i created a separate section to highlight the importance. good idea on the <2min to align with ec2's 2min warning + EMR does not assign new tasks to nodes that have the 2 min warning. 

```
Reduce individual task run time - shorter running tasks means the impact of a spot interruption is less because the amount of time to recompute is less.
```

**Comment by secretazianman** [comment]
I did see that. I just thought it was neat that in this specific case, hardly any recompute is needed in the first place. Because the tasks finish so quick.

**Comment by mattliemAWS** [comment]
yup, the <2min task is a great recommendation. thanks!
